import sanitizeHtml from 'sanitize-html';

const SANITIZE_OPTIONS: sanitizeHtml.IOptions = {
  allowedTags: [
    'a',
    'abbr',
    'address',
    'b',
    'big',
    'blockquote',
    'br',
    'caption',
    'center',
    'cite',
    'code',
    'col',
    'colgroup',
    'dd',
    'del',
    'div',
    'dl',
    'dt',
    'em',
    'figcaption',
    'figure',
    'font',
    'h1',
    'h2',
    'h3',
    'h4',
    'h5',
    'h6',
    'hr',
    'i',
    'img',
    'ins',
    'li',
    'mark',
    'ol',
    'p',
    'pre',
    's',
    'small',
    'span',
    'strike',
    'strong',
    'sub',
    'sup',
    'table',
    'tbody',
    'td',
    'tfoot',
    'th',
    'thead',
    'tr',
    'u',
    'ul',
  ],
  allowedAttributes: {
    a: ['href', 'name', 'target', 'rel', 'title'],
    img: ['src', 'alt', 'width', 'height', 'title', 'data-original-src'],
    font: ['color', 'face', 'size'],
    '*': ['class', 'style', 'align', 'valign', 'dir', 'width', 'height', 'bgcolor'],
    table: ['cellpadding', 'cellspacing', 'border', 'width', 'height', 'bgcolor', 'align'],
    col: ['span', 'width'],
    colgroup: ['span', 'width'],
    td: ['colspan', 'rowspan', 'align', 'valign', 'width', 'height', 'bgcolor'],
    th: ['colspan', 'rowspan', 'align', 'valign', 'width', 'height', 'bgcolor'],
    tr: ['align', 'valign', 'bgcolor', 'height'],
  },
  allowedSchemes: ['http', 'https', 'mailto', 'tel'],
  allowedSchemesByTag: {
    img: ['http', 'https', 'data', 'cid'],
  },
  allowedSchemesAppliedToAttributes: ['href', 'src'],
  allowProtocolRelative: false,
  disallowedTagsMode: 'discard',
  allowedStyles: {
    '*': {
      color: [/.*/],
      'background-color': [/.*/],
      background: [/^(?!.*url\().*$/i],
      'text-align': [/.*/],
      'text-decoration': [/.*/],
      'text-transform': [/.*/],
      'text-indent': [/.*/],
      'vertical-align': [/.*/],
      'white-space': [/.*/],
      direction: [/.*/],
      'font-family': [/.*/],
      'font-size': [/.*/],
      'font-weight': [/.*/],
      'font-style': [/.*/],
      'line-height': [/.*/],
      'letter-spacing': [/.*/],
      'list-style': [/.*/],
      'list-style-type': [/.*/],
      width: [/.*/],
      height: [/.*/],
      'min-width': [/.*/],
      'max-width': [/.*/],
      'min-height': [/.*/],
      'max-height': [/.*/],
      display: [/.*/],
      float: [/.*/],
      clear: [/.*/],
      overflow: [/.*/],
      padding: [/.*/],
      'padding-top': [/.*/],
      'padding-right': [/.*/],
      'padding-bottom': [/.*/],
      'padding-left': [/.*/],
      margin: [/.*/],
      'margin-top': [/.*/],
      'margin-right': [/.*/],
      'margin-bottom': [/.*/],
      'margin-left': [/.*/],
      border: [/.*/],
      'border-top': [/.*/],
      'border-right': [/.*/],
      'border-bottom': [/.*/],
      'border-left': [/.*/],
      'border-color': [/.*/],
      'border-width': [/.*/],
      'border-style': [/.*/],
      'border-radius': [/.*/],
      'border-collapse': [/.*/],
      'border-spacing': [/.*/],
    },
  },
  transformTags: {
    a: (_tag, attribs) => ({
      tagName: 'a',
      attribs: {
        ...attribs,
        target: '_blank',
        rel: 'noopener noreferrer nofollow',
      },
    }),
    img: (_tag, attribs) => {
      const src = attribs.src ?? '';
      const isRemote = /^https?:/i.test(src);
      if (isRemote) {
        return {
          tagName: 'img',
          attribs: {
            ...attribs,
            src: 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxIiBoZWlnaHQ9IjEiLz4=',
            'data-original-src': src,
            alt: attribs.alt ?? 'Remote image (blocked)',
          },
        };
      }
      return { tagName: 'img', attribs };
    },
  },
};

export function sanitizeMessageHtml(html: string): string {
  if (!html) return '';
  return sanitizeHtml(html, SANITIZE_OPTIONS);
}
