name = "zumasia-db-mail"
compatibility_date = "2026-06-01"

[[d1_databases]]
binding = "DB"
database_name = "zumasia-mail"
database_id = "12749b24-b21d-4f5d-bbca-89321113db93"
migrations_dir = "migrations"
